language: java
jdk:
- openjdk8

install: skip

before_script:
- sudo service mysql stop
- gem install asciidoctor-pdf --pre

script:
- "./build_poh.sh"

before_deploy:
- curl https://github.com/lindell/github-release-cli/releases/download/1.3.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser
- export BODY=$(envsubst < ./CHANGELOG.md)
- export OH_FULL_PKG=$(ls OpenHospital-*.zip)
- export POH_LINUX32_PKG=$(ls poh-linux-x32-*.tar.gz)
- export POH_LINUX64_PKG=$(ls poh-linux-x64-*.tar.gz)
- export POH_WIN32_PKG=$(ls poh-win32-*.zip)
- export PACKAGES=$(ls *.zip *.tar.gz | sed 's/ /*/g')

deploy:
  provider: script
  script: "./github-releaser -draft -verbose"
  skip_cleanup: true
  file: {"${OH_FULL_PKG}","${POH_LINUX32_PKG}","${POH_LINUX64_PKG}","${POH_WIN32_PKG}"} 
  overwrite: true
  on:
    tags: true
    
env:
  global:
  - secure: ua8YazECiHfUyqYP4Av+qy/OJAZE9ok/rGVJnEGIsAOGi+adDWV9iYZLdnNBqINbBbAT599DmfSr61e18wH8MFYpLKV9M8l+bKy8aZB7fCxt+gPvtOl9kwZaI1rscgwEunZdgqP+obBBm8oaO97R+PruWiH5UOrffr5RetdZ9iSLTEaqOCvGwya49r9IPpvj2ejWFDyq092Xw+zh4pO4REsFaPFs9HGWrxHfKN3MXNPao5miCqRrk94iIMSJifvDwqcdrhDVvnrjCxcQVJ0wh9BnX692N1xem/TJhYk6NhyVysbGkC3FVak4kDmgLem7bz1t40j8qo5Sz5nwjn74h/xa7YomdoI0tQlIx467rpQgk3Q2bW15vKNGQQ/evaMydhDq4QGO9paeYTsDpiMtEq3GDvH0CXelwUjlbd20U0prL+1yXNTGrI1k1Z2cMdCkI8JJU+2C9IA3B2G0rrx7EBgD1MlNLmSzNLtml82B/kRy4ciXX+16mCZo3h6rqltbkVMOqdAoVwChdAt7VQk1OEhxKVpeXuCQBdUyVHUbfT2bwg0Vo2IHehb5zK1gsayNxGrSSPK8RGiqO96qSjxIiR60up3WnfL7P/0FKbCZYJ8OWqxETT7r9/bcd4QFNS9OZyPNIxNcCoU5CEOyMvLWwRV/b/wEkM7gn/Uk3gS76p8=
